In [2]:
import pandas as pd
import numpy as np

In [4]:
pam_data = pd.read_csv('C:/Users/mdbla/Documents/UW-Capstone/PAM194_Keratino_CytoPanel_1/PAM194_Keratino_CytoPanel_1/pam194ObjPerinuclear.csv')

pam_data

,ImageNumber,ObjectNumber,Metadata_Date,Metadata_FileLocation,Metadata_Frame,Metadata_Metadata_Cytokine,Metadata_Metadata_Dose,Metadata_Plate,Metadata_Run,Metadata_Series,...,Texture_Contrast_CorrMito_3_02_256,Texture_Contrast_CorrMito_3_03_256,Texture_Contrast_CorrNileRed_3_00_256,Texture_Contrast_CorrNileRed_3_01_256,Texture_Contrast_CorrNileRed_3_02_256,Texture_Contrast_CorrNileRed_3_03_256,Texture_Contrast_CorrWGA_3_00_256,Texture_Contrast_CorrWGA_3_01_256,Texture_Contrast_CorrWGA_3_02_256,Texture_Contrast_CorrWGA_3_03_256
0,1,1,NaN,NaN,0,IFNg,33,Plate 1,NaN,0,...,163.029630,172.681729,41.057348,49.278530,51.725926,64.186640,305.080645,409.651838,432.438889,386.387033
1,1,2,NaN,NaN,0,IFNg,33,Plate 1,NaN,0,...,735.050114,971.266504,204.086364,228.314904,189.419134,298.246944,1441.497727,2273.656250,1459.938497,1205.997555
2,1,3,NaN,NaN,0,IFNg,33,Plate 1,NaN,0,...,857.140171,929.469945,73.214162,93.752747,72.317949,80.058288,3096.525043,5232.263736,2797.174359,2538.302368
3,1,4,NaN,NaN,0,IFNg,33,Plate 1,NaN,0,...,751.958333,948.933649,41.334815,81.787736,81.738095,90.276461,977.817778,1993.136792,1493.849702,1703.658768
4,1,5,NaN,NaN,0,IFNg,33,Plate 1,NaN,0,...,1294.931868,1797.672131,77.267819,94.722353,88.406593,130.035129,2478.924406,3199.548235,2603.863736,3415.674473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90770,408,201,NaN,NaN,0,IL26,11,Plate 3,NaN,0,...,30.288177,29.227749,50.706601,88.672872,59.603448,59.725131,69.496333,122.763298,96.704433,104.392670
90771,408,202,NaN,NaN,0,IL26,11,Plate 3,NaN,0,...,515.683502,190.661597,466.815700,1325.119718,407.023569,71.007605,547.228669,1333.334507,370.313131,279.939163
90772,408,203,NaN,NaN,0,IL26,11,Plate 3,NaN,0,...,162.351695,307.095023,47.650215,55.217090,41.584746,40.409502,191.412017,182.588915,144.881356,134.692308
90773,408,204,NaN,NaN,0,IL26,11,Plate 3,NaN,0,...,183.078829,400.424390,83.993333,124.195704,153.921171,227.141463,191.051111,227.515513,298.472973,496.858537
90774,408,205,NaN,NaN,0,IL26,11,Plate 3,NaN,0,...,73.369412,98.565657,41.808962,56.535354,40.644706,53.583333,113.794811,151.540404,98.701176,107.267677

In [5]:
pam_data.columns

Index(['ImageNumber', 'ObjectNumber', 'Metadata_Date', 'Metadata_FileLocation',
       'Metadata_Frame', 'Metadata_Metadata_Cytokine',
       'Metadata_Metadata_Dose', 'Metadata_Plate', 'Metadata_Run',
       'Metadata_Series',
       ...
       'Texture_Contrast_CorrMito_3_02_256',
       'Texture_Contrast_CorrMito_3_03_256',
       'Texture_Contrast_CorrNileRed_3_00_256',
       'Texture_Contrast_CorrNileRed_3_01_256',
       'Texture_Contrast_CorrNileRed_3_02_256',
       'Texture_Contrast_CorrNileRed_3_03_256',
       'Texture_Contrast_CorrWGA_3_00_256',
       'Texture_Contrast_CorrWGA_3_01_256',
       'Texture_Contrast_CorrWGA_3_02_256',
       'Texture_Contrast_CorrWGA_3_03_256'],
      dtype='object', length=121)

In [16]:
# QUESTION FOR SPONSORS: We're supposed to have three doeses per cytokine: 11ml, 33ml, and 100ml. 
# Yet we have a dose of 0ml listed that has measurements. Why do we have this? Does it serve as a baseline?

pam_data['Metadata_Metadata_Dose'].unique()

array([ 33,  11, 100,   0], dtype=int64)

In [17]:
pam_data[pam_data['Metadata_Metadata_Dose'] == 0]

,ImageNumber,ObjectNumber,Metadata_Date,Metadata_FileLocation,Metadata_Frame,Metadata_Metadata_Cytokine,Metadata_Metadata_Dose,Metadata_Plate,Metadata_Run,Metadata_Series,...,Texture_Contrast_CorrMito_3_02_256,Texture_Contrast_CorrMito_3_03_256,Texture_Contrast_CorrNileRed_3_00_256,Texture_Contrast_CorrNileRed_3_01_256,Texture_Contrast_CorrNileRed_3_02_256,Texture_Contrast_CorrNileRed_3_03_256,Texture_Contrast_CorrWGA_3_00_256,Texture_Contrast_CorrWGA_3_01_256,Texture_Contrast_CorrWGA_3_02_256,Texture_Contrast_CorrWGA_3_03_256
18299,73,1,NaN,NaN,0,untr,0,Plate 1,NaN,0,...,550.467811,901.825986,78.820513,119.722727,106.251073,146.030162,278.408120,300.379545,207.362661,360.651972
18300,73,2,NaN,NaN,0,untr,0,Plate 1,NaN,0,...,433.908847,808.122449,91.374332,129.517241,99.104558,171.944606,146.671123,229.847701,137.852547,199.463557
18301,73,3,NaN,NaN,0,untr,0,Plate 1,NaN,0,...,942.519751,2780.346067,145.671579,150.995506,63.960499,169.105618,1104.115789,902.422472,367.309771,1605.606742
18302,73,4,NaN,NaN,0,untr,0,Plate 1,NaN,0,...,100.038031,217.352518,140.736486,173.169082,88.543624,203.395683,278.225225,304.676329,183.590604,361.774580
18303,73,5,NaN,NaN,0,untr,0,Plate 1,NaN,0,...,1925.761317,3860.026490,321.796334,381.997831,283.460905,490.657837,409.759674,368.735358,673.259259,1159.770419
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84224,372,174,NaN,NaN,0,untr,0,Plate 3,NaN,0,...,103.576336,126.714286,35.612782,102.939516,92.643130,88.697959,35.730189,92.129555,82.136015,73.730061
84225,372,175,NaN,NaN,0,untr,0,Plate 3,NaN,0,...,1212.082126,2465.690104,59.980583,71.769634,56.210145,95.078125,490.723301,700.039267,417.538647,648.674479
84226,372,176,NaN,NaN,0,untr,0,Plate 3,NaN,0,...,1620.845783,2174.795866,55.000000,106.580729,48.284337,45.087855,384.966427,755.057292,325.361446,358.180879
84227,372,177,NaN,NaN,0,untr,0,Plate 3,NaN,0,...,1744.568932,3222.661191,40.883946,43.912317,42.234951,43.336756,187.864603,228.056367,119.891262,216.039014
84228,372,178,NaN,NaN,0,untr,0,Plate 3,NaN,0,...,2699.005747,4168.445141,306.831933,425.049383,325.942529,560.109718,1071.865546,2842.768519,2561.454023,3349.373041

In [18]:
# QUESTION FOR TEAM: Do we need to include the wells in our analyses? I personally don't see a need for them

pam_data['Metadata_Well'].unique()

array(['B10', 'B11', 'B2', 'B3', 'B4', 'B9', 'C10', 'C11', 'C2', 'C3',
       'C4', 'C9', 'D6', 'D7', 'F10', 'F11', 'F2', 'F3', 'F4', 'F9',
       'G10', 'G11', 'G2', 'G3', 'G4', 'G9'], dtype=object)

In [23]:
# QUESTION FOR TEAM: For all of our datasets, I'm thinking we only need to include the image number, object number,
# cytokine, dose, plate, and measurements. Is there a reason we should keep the other columns?

# I think the run ID should also be included, but this isn't listed in our data for some reason. Do you think we may 
# need it?

pam_data['Metadata_Run'].unique()

array([nan])