In [1]:
import pandas as pd
import numpy as np

References:
- https://www.geeksforgeeks.org/python-pandas-dataframe-corr/#
- https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corr.html
- https://stackoverflow.com/questions/15854878/correlation-between-columns-in-dataframe?noredirect=1&lq=1
- https://stackoverflow.com/questions/13187778/convert-pandas-dataframe-to-numpy-array

In [2]:
# get some data to experiment with
df_data = pd.read_csv('../../data/heatmap/pam194ObjPerinuclear_lo.csv')
df_data

,Unnamed: 0,ImageNumber,Metadata_Metadata_Cytokine,Metadata_Metadata_Dose,Metadata_Plate,Metadata_Well,Granularity_1_CorrActin,Granularity_1_CorrDNA2,Granularity_1_CorrGolgi,Granularity_1_CorrMito,...,Texture_Contrast_CorrMito_3_02_256,Texture_Contrast_CorrMito_3_03_256,Texture_Contrast_CorrNileRed_3_00_256,Texture_Contrast_CorrNileRed_3_01_256,Texture_Contrast_CorrNileRed_3_02_256,Texture_Contrast_CorrNileRed_3_03_256,Texture_Contrast_CorrWGA_3_00_256,Texture_Contrast_CorrWGA_3_01_256,Texture_Contrast_CorrWGA_3_02_256,Texture_Contrast_CorrWGA_3_03_256
0,0,1,IFNg,33,Plate 1,B10,39.085821,65.349797,29.429464,30.085395,...,163.029630,172.681729,41.057348,49.278530,51.725926,64.186640,305.080645,409.651838,432.438889,386.387033
1,1,1,IFNg,33,Plate 1,B10,40.965732,52.025753,26.951641,12.008458,...,735.050114,971.266504,204.086364,228.314904,189.419134,298.246944,1441.497727,2273.656250,1459.938497,1205.997555
2,2,1,IFNg,33,Plate 1,B10,26.494443,23.842541,31.133865,16.847527,...,857.140171,929.469945,73.214162,93.752747,72.317949,80.058288,3096.525043,5232.263736,2797.174359,2538.302368
3,3,1,IFNg,33,Plate 1,B10,38.945234,37.122993,23.805090,18.204408,...,751.958333,948.933649,41.334815,81.787736,81.738095,90.276461,977.817778,1993.136792,1493.849702,1703.658768
4,4,1,IFNg,33,Plate 1,B10,33.282087,71.535983,23.379080,23.507941,...,1294.931868,1797.672131,77.267819,94.722353,88.406593,130.035129,2478.924406,3199.548235,2603.863736,3415.674473
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90770,90770,408,IL26,11,Plate 3,G4,50.947386,77.122015,56.485296,34.056229,...,30.288177,29.227749,50.706601,88.672872,59.603448,59.725131,69.496333,122.763298,96.704433,104.392670
90771,90771,408,IL26,11,Plate 3,G4,28.208099,60.537623,23.617386,11.559977,...,515.683502,190.661597,466.815700,1325.119718,407.023569,71.007605,547.228669,1333.334507,370.313131,279.939163
90772,90772,408,IL26,11,Plate 3,G4,41.707302,56.017830,29.110699,26.664141,...,162.351695,307.095023,47.650215,55.217090,41.584746,40.409502,191.412017,182.588915,144.881356,134.692308
90773,90773,408,IL26,11,Plate 3,G4,22.225451,69.847256,20.070489,11.952982,...,183.078829,400.424390,83.993333,124.195704,153.921171,227.141463,191.051111,227.515513,298.472973,496.858537
90774,90774,408,IL26,11,Plate 3,G4,25.360900,70.275641,34.553813,26.440437,...,73.369412,98.565657,41.808962,56.535354,40.644706,53.583333,113.794811,151.540404,98.701176,107.267677

Get a small dataset

In [3]:
df_data_small = df_data.iloc[0:5, 5:10]
df_data_small

,Metadata_Well,Granularity_1_CorrActin,Granularity_1_CorrDNA2,Granularity_1_CorrGolgi,Granularity_1_CorrMito
0,B10,39.085821,65.349797,29.429464,30.085395
1,B10,40.965732,52.025753,26.951641,12.008458
2,B10,26.494443,23.842541,31.133865,16.847527
3,B10,38.945234,37.122993,23.805090,18.204408
4,B10,33.282087,71.535983,23.379080,23.507941

Get the correlation

In [4]:
corr_df = df_data_small.corr(numeric_only=True)
corr_df

,Granularity_1_CorrActin,Granularity_1_CorrDNA2,Granularity_1_CorrGolgi,Granularity_1_CorrMito
Granularity_1_CorrActin,1.000000,0.448911,-0.393099,0.041187
Granularity_1_CorrDNA2,0.448911,1.000000,-0.401912,0.587078
Granularity_1_CorrGolgi,-0.393099,-0.401912,1.000000,0.052442
Granularity_1_CorrMito,0.041187,0.587078,0.052442,1.000000

Pair-wise Correlation Function

Granularity_1_CorrActin, Granularity_1_CorrActin = 1.0000000
Granularity_1_CorrActin, Granularity_1_CorrDNA2 = 0.448911

In [5]:
def corr_pairs(df):
    
    # compute correlation
    corr_df = df.corr(numeric_only=True) #will this still work if user passes nonnumeric?
    
    # reshape the data into a single column
    corr_array = corr_df.to_numpy()
    corr_array = np.reshape(a=corr_array, newshape=(-1, 1))
    
#     feature_names = df.columns.to_list()
    feature_names = corr_df.columns.to_list()
    
    print(feature_names)
    
    num_features = len(feature_names)
    new_df_rows = []
    corr_idx = 0
    
    print('number of features: {}'.format(num_features))
    
    # construct rows of new dataframe
    for i in range(num_features):
        for j in range(num_features):
#             print('i, j are: {}, {}'.format(i,j))
#             print('index is: {}'.format(corr_idx))
            if i == j: # we can throw out the entries for the correlation of a feature with itself
                corr_idx += 1
            else: #construct a row
                corr_value = corr_array[corr_idx]
                # Reference: https://stackoverflow.com/questions/8220702/how-to-fix-typeerror-int-object-is-not-subscriptable
                new_row = [feature_names[i], feature_names[j], corr_value[0]]
                new_df_rows.append(new_row)
                
                corr_idx += 1
    
    # combine rows into new dataframe
    pairwise_df = pd.DataFrame(data=new_df_rows, columns=['Feature_1', 'Feature_2', 'Correlation'])
    
    return pairwise_df

In [6]:
# test it out
pair_df = corr_pairs(df_data_small)
pair_df

['Granularity_1_CorrActin', 'Granularity_1_CorrDNA2', 'Granularity_1_CorrGolgi', 'Granularity_1_CorrMito']
number of features: 4

                  Feature_1                Feature_2  Correlation
0   Granularity_1_CorrActin   Granularity_1_CorrDNA2     0.448911
1   Granularity_1_CorrActin  Granularity_1_CorrGolgi    -0.393099
2   Granularity_1_CorrActin   Granularity_1_CorrMito     0.041187
3    Granularity_1_CorrDNA2  Granularity_1_CorrActin     0.448911
4    Granularity_1_CorrDNA2  Granularity_1_CorrGolgi    -0.401912
5    Granularity_1_CorrDNA2   Granularity_1_CorrMito     0.587078
6   Granularity_1_CorrGolgi  Granularity_1_CorrActin    -0.393099
7   Granularity_1_CorrGolgi   Granularity_1_CorrDNA2    -0.401912
8   Granularity_1_CorrGolgi   Granularity_1_CorrMito     0.052442
9    Granularity_1_CorrMito  Granularity_1_CorrActin     0.041187
10   Granularity_1_CorrMito   Granularity_1_CorrDNA2     0.587078
11   Granularity_1_CorrMito  Granularity_1_CorrGolgi     0.052442

### Other Experiments

First let's see what happens if you pass a feature with no variance into the corr function.

In [7]:
df_data_small = df_data.iloc[0:5, 3:10]
df_data_small

,Metadata_Metadata_Dose,Metadata_Plate,Metadata_Well,Granularity_1_CorrActin,Granularity_1_CorrDNA2,Granularity_1_CorrGolgi,Granularity_1_CorrMito
0,33,Plate 1,B10,39.085821,65.349797,29.429464,30.085395
1,33,Plate 1,B10,40.965732,52.025753,26.951641,12.008458
2,33,Plate 1,B10,26.494443,23.842541,31.133865,16.847527
3,33,Plate 1,B10,38.945234,37.122993,23.805090,18.204408
4,33,Plate 1,B10,33.282087,71.535983,23.379080,23.507941

In [8]:
df_data_small.drop(columns=['Metadata_Plate', 'Metadata_Well'], inplace=True)
df_data_small

,Metadata_Metadata_Dose,Granularity_1_CorrActin,Granularity_1_CorrDNA2,Granularity_1_CorrGolgi,Granularity_1_CorrMito
0,33,39.085821,65.349797,29.429464,30.085395
1,33,40.965732,52.025753,26.951641,12.008458
2,33,26.494443,23.842541,31.133865,16.847527
3,33,38.945234,37.122993,23.805090,18.204408
4,33,33.282087,71.535983,23.379080,23.507941

In [10]:
corr_pairs(df_data_small)

['Metadata_Metadata_Dose', 'Granularity_1_CorrActin', 'Granularity_1_CorrDNA2', 'Granularity_1_CorrGolgi', 'Granularity_1_CorrMito']
number of features: 5

                  Feature_1                Feature_2  Correlation
0    Metadata_Metadata_Dose  Granularity_1_CorrActin          NaN
1    Metadata_Metadata_Dose   Granularity_1_CorrDNA2          NaN
2    Metadata_Metadata_Dose  Granularity_1_CorrGolgi          NaN
3    Metadata_Metadata_Dose   Granularity_1_CorrMito          NaN
4   Granularity_1_CorrActin   Metadata_Metadata_Dose          NaN
5   Granularity_1_CorrActin   Granularity_1_CorrDNA2     0.448911
6   Granularity_1_CorrActin  Granularity_1_CorrGolgi    -0.393099
7   Granularity_1_CorrActin   Granularity_1_CorrMito     0.041187
8    Granularity_1_CorrDNA2   Metadata_Metadata_Dose          NaN
9    Granularity_1_CorrDNA2  Granularity_1_CorrActin     0.448911
10   Granularity_1_CorrDNA2  Granularity_1_CorrGolgi    -0.401912
11   Granularity_1_CorrDNA2   Granularity_1_CorrMito     0.587078
12  Granularity_1_CorrGolgi   Metadata_Metadata_Dose          NaN
13  Granularity_1_CorrGolgi  Granularity_1_CorrActin    -0.393099
14  Granularity_1_CorrGolgi   Granularity_1_CorrDNA2    -0.401912
15  Granularity_1_CorrGolgi   Granularity_1_CorrMito     0.052442
16   Granularity_1_CorrMito   Metadata_Metadata_Dose          NaN
17   Granularity_1_CorrMito  Granularity_1_CorrActin     0.041187
18   Granularity_1_CorrMito   Granularity_1_CorrDNA2     0.587078
19   Granularity_1_CorrMito  Granularity_1_CorrGolgi     0.052442

dataframe.corr() returns NaN for correlations involving features with no variance.

### Now, let's see what happens if the user provides a non-numeric feature

In [12]:
df_data_small = df_data.iloc[0:5, 5:10]
df_data_small

,Metadata_Well,Granularity_1_CorrActin,Granularity_1_CorrDNA2,Granularity_1_CorrGolgi,Granularity_1_CorrMito
0,B10,39.085821,65.349797,29.429464,30.085395
1,B10,40.965732,52.025753,26.951641,12.008458
2,B10,26.494443,23.842541,31.133865,16.847527
3,B10,38.945234,37.122993,23.805090,18.204408
4,B10,33.282087,71.535983,23.379080,23.507941

In [13]:
df_data_small.iloc[0,0]

'B10'

In [14]:
type(df_data_small.iloc[0,0])

str

In [15]:
corr_pairs(df_data_small)

['Granularity_1_CorrActin', 'Granularity_1_CorrDNA2', 'Granularity_1_CorrGolgi', 'Granularity_1_CorrMito']
number of features: 4

                  Feature_1                Feature_2  Correlation
0   Granularity_1_CorrActin   Granularity_1_CorrDNA2     0.448911
1   Granularity_1_CorrActin  Granularity_1_CorrGolgi    -0.393099
2   Granularity_1_CorrActin   Granularity_1_CorrMito     0.041187
3    Granularity_1_CorrDNA2  Granularity_1_CorrActin     0.448911
4    Granularity_1_CorrDNA2  Granularity_1_CorrGolgi    -0.401912
5    Granularity_1_CorrDNA2   Granularity_1_CorrMito     0.587078
6   Granularity_1_CorrGolgi  Granularity_1_CorrActin    -0.393099
7   Granularity_1_CorrGolgi   Granularity_1_CorrDNA2    -0.401912
8   Granularity_1_CorrGolgi   Granularity_1_CorrMito     0.052442
9    Granularity_1_CorrMito  Granularity_1_CorrActin     0.041187
10   Granularity_1_CorrMito   Granularity_1_CorrDNA2     0.587078
11   Granularity_1_CorrMito  Granularity_1_CorrGolgi     0.052442

It ignores non numeric features.